### ISSUE TITLE
Team Retrospectives

### ISSUE THREAD

**Issue by gabrielvbarney** [CSC307-W2020-Team6/307-Sec01-Team6#25]
# What went well last week?
- We were able to come together and do the necessary research to get the ball rolling on our project, Lynk Up! We also identified all features and work items that we deemed necessary to implement, and will assign them to future sprints.
# What didn't go well last week?
- Due to the winter career fair/interviews and assimilating to the hustle of winter quarter, we had some scheduling issues that prevented us from getting an early start in planning and research. 
# What experiment (or change) we'll make next week to improve as a team?
- With the career fair being done and as we more-so assimilate to winter quarter, we will have more time to be able to work on our project. We also now realize the importance of setting time aside to make progress on Lynk Up!, so more devotion will be put towards this.

**Comment by gabrielvbarney** [comment]
# What went well last week?
- We began the software development cycle of LyncUp!. We were able to identify quickly that a different database should be used for our project, so we began to learn about and implement a database with MySQL. Also, we properly storyboarded, and created wireframes for our UI. And finally, we were able to get a working URL for our program.
# What didn't go well last week?
- Unfortunately, due to the unforeseen circumstances, we were unable to completely finish any of the work items in our Sprint 1 backlog.
# What experiment (or change) we'll make next week to improve as a team?
- Since we now have everything sorted out (for now), we will continue to work on the items in Sprint 1, and when those are finished, begin to work on other features. The main thing that we will change to improve is putting more hours of rigorous development in throughout the week, rather than waiting for the weekend.

**Comment by gabrielvbarney** [comment]
## What went well last week?
- Our log-in screen was created using HTML. It is not necessarily fully-functioning yet, however, aesthetically it is sound. It is on track to be fully functioning within the next few days. Also, we have a database that we can insert to and retrieve items from. Within the next few days as more work items are implemented, it will be adjusted to hold more attributes about each user.

## What didn't go last week?
- We discovered that with considering the scale of our project, AngularJS (our original frame-work for front-end development), would not be ideal. With that being said, we are now going to use React. With React we have the ability to choose which libraries to implement, and would overall be more conducive to our project. This change has set us back just a bit, but we are planning to catch up within this next week. 

## What experiment (or change) we'll make next week to improve as a team?
- As stated previously, we are a bit behind in the development of our program. To combat this, we will be putting in extra time this week to get to where we should be. We now have an even more sound feel of how our program should work, so we are confident in our ability to make progress moving forward.

**Comment by rmete** [comment]
# What things went well last week? 

- We as a team got on the same page in terms of what we need to do and what framework we are using. At first, we were trying to use two separate frameworks, but we decided to stick to just one: Django. Our database is up and running and now we all have a running local copy of the database on our personal machines. The Google Calendar API is almost integrated, and test cases have been made to test our database. 


# What didn't go last week?

- We discovered that we were not all on the same page with what we were doing. Because of this, we had to change our frameworks and stick to only using Django. This made us fall a little behind as we lost some of our work; however, I believe things will now go smoothly as we all have a more coherent understanding of what our task is.


# What experiment (or change) we'll make next week to improve as a team?
- I believe meeting up and working together will really help our team prosper. This will enable us to have better communication which will lead to a better understanding of each other's code.

**Comment by gabrielvbarney** [comment]
## What went well last week?
- Almost everything that we did this previous week went well. We now have a well structured standing program, and we are on track to finish before the due date. We did have to make a few changes to our project planning (group calendar interface changed to a list of each user's unavailable times), but we do believe what we are planning now will be successful. 

## What didn't go well last week?
- Aside from changing a feature in our program, everything went smoothly and it is now clear how we are going to finish our project.

## What experiment (or change) we'll make next week to improve as a team?
- We will begin to develop different features/work items separately as opposed to together like we did this week. Now that we are all on the same page, we all have an understanding of what is necessary to build this software piece by piece. We are also going to use github more frequently.

**Comment by gabrielvbarney** [comment]
## What went well last week?
- We were able to continue to make steady progress on the completion of our program. It was not as significant as the progress made in the previous week, but it was still a movement in the right direction. We also began looking into Selenium Automation and should have that finished by tonight (3/1). 

## What didn't go well last week?
- Because it is so late in the quarter, each of us have a lot going on. I myself had SLO Hacks this weekend, which limited the amount of time we were able to devote to our project this week.

## What experiment (or change) we'll make next week to improve as a team?
- There's not much more to say other than the fact that we will continue to work progressively on our project. We will also attempt to devote more time, and due to the fact that SLO Hacks is over, we will most likely spend a majority of next weekend putting the final touches on our program.

**Comment by MJaojoco** [comment]
## What went well last week?
- This week we were able to finish a fair amount of work items. We made 2 new models(Group and Friend) with different basic associated views(List, Detail, Create, Delete, Update). This will allow registered users to communicate with each other using our app. 

## What didn't go well last week?
- A couple of our views associated with friends are not yet fully functionally. We also made little to no progress on the overlaying of availability between group members, which is a key feature of our project. We had very little time to meet as a full team so we were rarely ever on the same page this past week. We also had a bug stemming from the fact that we were running different versions of django on our personal work stations, so that prevented us from completing work individually until we decided on which version to use as a group. 

## What experiment (or change) we'll make next week to improve as a team?
- Moving forward we will continue to work on our website and implement new features. We will also be using GitHub's project boards more actively as a means of sharing/communicating our progress.
